services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: popup
    networks:
      - docker-network
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Redis의 기본 포트
    volumes:
      - redis-data:/data  # Redis 데이터 저장
    networks:
      - docker-network

  spring-app:
    build:
      context: ./backend
    container_name: popupstore-container
    depends_on:
      - mysql
    networks:
      - docker-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/popup
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  fastapi-app:
    build:
      context: ./ai
      dockerfile: Dockerfile # 명시적 Dockerfile 경로
    container_name: fastapi-app-container
    ports:
      - "8000:8000"
    networks:
      - docker-network
    environment:
      AUTO_CATEGORY_KEY: sk-proj-VXwcPzlcS0gr1vjm62FVT3BlbkFJHgphK3z9HJbEJ0JdTLyw

networks:
  docker-network:
    driver: bridge

volumes:
  redis-data: