[supervisord]
nodaemon=true

[program:category_recommend]
command=uvicorn category_recommend.Combine:app --host 0.0.0.0 --port 8000 --reload
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/category_recommend.err.log
stdout_logfile=/var/log/category_recommend.out.log

[program:store_recommend]
command=uvicorn store_recommend.main:app --host 0.0.0.0 --port 8001 --reload
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/store_recommend.err.log
stdout_logfile=/var/log/store_recommend.out.log